### ISSUE TITLE
Relative URL's don't work properly

### ISSUE THREAD

**Issue by zephor** [http-party/http-server#39]
According to http://www.w3.org/TR/WD-html40-970917/htmlweb.html#h-5.1.3 a relative URL should resolve to the current directory.   However it seems the server ignores the current directory and appends directly to the domain.  This is problematic for relative links in html.

For example:

on http://domain/page/index.html

<code>&lt;a href='text.html'&gt;</code>should resolve to **http://domain/page/test.html**.  However currently it resolves to **http://domain/test.html**.

Investigation shows that this works properly with just union and ecstatic.

**Comment by emptyshells** [comment]
This is a different use case.  But files that reside outside of the public directory that are referenced by index.html in public/index.html cannot be resolved, and are resolving to absolute paths as if they existed inside the public directory.

Is this the intended use case?

File structure:

```
--dist
----browser.js
--public
----index.html
```

```html
<html>
<head>
</head>
<body>
  <script type="text/javascript" src="../dist/browser.js"></script>
</body>
</html>
```

Console output
```bash
[Thu Feb 07 2019 08:07:46 GMT-0600 (CST)] "GET /dist/browser.js" Error (404): "Not found"
```

**Comment by thornjad** [comment]
@emptyshells that is intended behavior, because the `public/` directory is served by default if it exists, and anything outside of that directory is inaccessible to the server. This is for security, since obviously you don't want to serve your entire file system. In this case, it's resolving to an absolute path because the `..` "hits" the root directory.

For your specific use case (looks like you're using browserify or something) you could either put `browser.js` inside the `public/` directory somewhere or drop the `public/` and put `index.html` at the same level as `dist/`.

**Comment by emptyshells** [comment]
@thornjad yes, thank you for the explanation.  I just ended up deploying the dist files to the public directory.

The security implication makes perfect sense.  I didn't think that all the way through.

**Comment by aderchox** [comment]
I have this issue. I'm referencing a file **inside the web root**. But yet relative paths in my javascript code don't work and all of them are assumed absolute, starting from the root.

For example:
```
lib/
    script.js
    test.svg
```
Now in the `script.js` if I set `imgElement.src = "test.svg";` it becomes a 404 not found (from the error shown in the console), but if I turn the path to `lib/test.svg` now it works. I've tried with `"./test.svg"` as well and it doesn't work either.

Any idea why!?
