### ISSUE TITLE
Startup notice did not show the right pure IPv6 url

### ISSUE THREAD

**Issue by codinggirl** [http-party/http-server#490]
Start up a server with IPv6 address, eg:

```
http-server -a ::1 -p 2011 docs-code
```

Bind a address like `::1`, it shows:    

    Starting up http-server, serving docs-code
    Available on:
      http://::1:2011
    Hit CTRL-C to stop the server

The link shown on console could not be opened, it should be opened via:

```
http://[::1]:2011
```

We should update the startup notice to fit it.

**Comment by BigBlueHat** [comment]
Good find! Would you be up for doing a PR?

**Comment by krlk89** [comment]
@BigBlueHat since it seems that OP did not act on this issue, I thought I could do it myself.
Though, I'm unsure what's the best way to check if the given address is IPv6, is checking for a ':' sufficient?

**Comment by thornjad** [comment]
While it takes a little more work to determine if an address is a _valid_ IP, I think checking for `:` should be good enough to decide it's IPv6 over IPv4. The only catch is that IPv4 can specify the port with a `:`, but port should be passed with `-p`.

**Comment by PavelSosin** [comment]
I'm in IPV6 network at office and at home. Startup notice shows me collection of IPV4 addresses and ports.
When I ask what is my IP I get my default IPV6 preferable IP.
When I try to use any of displayed addresses I get either "connection refused" or timeout.
Startin g from March 2020 Chrome will block https connections with all SSH security, tls1.0,tls1.1 certificates
For Chrome and Edge tls 1.3 is already the default. To allow lower security level browser has to be configured via Settings->Proxy->Advanced
Anyway, I'm limited to use http-server only locally because non-local http access will be blocked in our company soon.
Please, advise how to start http-server correctly.

**Comment by codinggirl** [comment]
Unfortunately, the tests about IPv6 in Travis-CI hang up.

**Comment by PavelSosin** [comment]
Maybe this post describes the solution. [http://code.danyork.com/2011/01/21/how-to-use-node-js-with-ipv6/](url)

**Comment by PavelSosin** [comment]
Curl to [::1] also reports connection refused:
curl:  Failed to connect to ::1 port 8080: Connection refused
my NodeJS ver 10 does support IPV6. NodeJS net server can be configured to accept only IPV4 but since Chrome on Windows 10 uses IPV6 as a default I would prefer http-server correction
