### ISSUE TITLE
Is there anyway to run this tool as service?

### ISSUE THREAD

**Issue by sandeepmeenuga** [http-party/http-server#550]
Is there anyway to run this tool as service?
So, I can use it even by closing the window too.

**Comment by thornjad** [comment]
Here's a good write-up of how to run a command as a service in Systemd: https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd#919059

I'm going to close this since this is an operating system question rather than specific to http-server, but please feel free to continue commenting!
