### ISSUE TITLE
need to run a nested index.html, but also need to import files from the root directory

### ISSUE THREAD

**Issue by ffan0811** [http-party/http-server#592]
![image](https://user-images.githubusercontent.com/37147911/71332418-858b7080-2579-11ea-93b2-2a0abe55e40f.png)

I'd like to run the highlighted ``index.html`` (in the image above) but it imports some files from the root directory. for example, it imports a file from ``/Content/styles/styles.min.css``

``index.html``
![image](https://user-images.githubusercontent.com/37147911/71332592-1bbf9680-257a-11ea-9755-f979241661b9.png)

However, it seems like http-server skips files which are outside of the ``index.html``. It gives me 404 not found error. am I doing something wrong or is there any other way to let http-server to start finding files from the root directory?

I run the ``index.html`` with the command line, ``http-server ./Publishing/`` in ``/PAY_INTEGRATED_ADMIN_SERVICE``

**Comment by thornjad** [comment]
To do this directly isn't something which is or will be supported, because only the directory being served (in this case, `Publishing/`) can ever be accessed. To serve anything else would be a _massive_ security hole in http-server, as it would necessarily give the client full access to your entire filesystem.

With your current directory structure, you _could_ serve the root of your project as the root of the server, and then in your browser go to `/Publishing/index.html`. However, this would give the client complete access to the entirety of your project, which you probably don't want.

A better solution would be to ensure that _all_ of the files you will ever serve to the client are in the same directory. You might move `/Content/styles/styles.min.css` into `/Publishing/styles/`, or move all of it to a single `webroot/` directory.

**Comment by thornjad** [comment]
I'm going to close this issue for now since this is intended behavior, but feel free to keep commenting and we can find a solution!
