### ISSUE TITLE
An option to set the base-href

### ISSUE THREAD

**Issue by zshlomyz** [http-party/http-server#595]
Hi,
I want to configure the http-server to listen to a URL that contain a virtual, like:
http:\/\/localhost:\<port\>\/\<virtual-path\>.
I can't find a way to doing that using the available options.
Is anyone know a way to do that?
Thanks

**Comment by thornjad** [comment]
I don't think I'm understanding what you'd like to do. Are you wanting to serve files in a way where you would go to `http://localhost:/.` in the browser? Or are you wanting to serve a file called `.`?

**Comment by zshlomyz** [comment]
Hi @thornjad , There was a problem with my question.
I fix that. I'll be happy if you can have another look to try help me.
Thanks

**Comment by thornjad** [comment]
What do you mean by virtual path? Are you wanting to be able to request something like `/foo/bar` even when the `foo/bar` file doesn't exist?

**Comment by zshlomyz** [comment]
What I want is to configure the http-server to respond to http:\/\/localhost:5000\/foo the same as if the request was http:\/\/localhost:5000.
For example:
- GET http:\/\/localhost:5000\/foo - the response will be the index.html file from the static files folder.
- GET http:\/\/localhost:5000\/foo/bar.css - the respond will be the bar.css file from the static files folder.

**Comment by thornjad** [comment]
Would you be able to achieve the same by simply putting all your files into a directory called "foo"?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zshlomyz** [comment]
No. There is any rewrite option that can help me?

**Comment by peterjhart** [comment]
@zshlomyz See #542, #318

**Comment by culmat** [comment]
this seems to be a duplicate of #294

**Comment by thornjad** [comment]
I'm considering this a duplicate of #139, please reopen if I've misunderstood the request

**Comment by sneakers-the-rat** [comment]
I think this is a different thing than #139, as I just came across it -- for example jekyll lets you set a `baseurl` configuration option for pages that are built and served from subdirectories of a website. 

For example if one had their blog at `https://mainurl.com/subpage/blog` then all the local links within the page will be, eg `<script src='/subpage/blog/asset.js'/>` even though you may be building into a temporary `_site` directory.

So currently, one could go into the `_site` directory and do `http-server` and get the html `index.html` file served correctly, but since all the local links to eg. js and css are `/subpage/blog/...` then you get 404's for all of them. 

Jekyll's server rewrites the url so that going to localhost:port/subpage/blog serves all the content from the `_site` root (so you don't need to build into artificial subdirectories)

webpack does something similar, so this would be very helpful for independent testing of bundled sites like that <3

**Comment by AnderssonPeter** [comment]
I'm guessing what they need is the ability to add a virtual folder that doesn't exist on disk.

So lets say I start `http-server` normally then requests to `http://localhost/text.txt` would go to `./text.txt` but if I add this parameter with the value `content` then I must request `http://localhost/content/text.txt` to get the same file, if i make any request without `/content/` I should get a 404.

In both cases the file is in the same path on disk but the path of the http request changes accordingly to the parameter, this is useful for angular applications where the `base-href` is set.

**Comment by it180171** [comment]
sdyffdsaf
