### ISSUE TITLE
bash: http-server: command not found

### ISSUE THREAD

**Issue by Articana** [http-party/http-server#626]
I've recently installed it on a Raspberry pi 3 using Raspbian and after some research and a reboot it still keeps promting that it is not found.

I've executed the following commands:
sudo npm install http-server -g

and this one for verification if it installed correctly:
npm list-g http-server
And it returned me this:
/opt/nodejs/lib
└── http-server@0.12.2 

Now, when i execute it to run a server i used this:
http-server -p 1234
 and still prompts me:
bash: http-server: command not found

**Comment by thornjad** [comment]
I believe the issue here is that you've installed with `sudo`, but then are trying to start the server without. To fix the immediate issue, try running `sudo http-server`.

In general, however, I recommend not installing anything from npm with sudo. While http-server won't abuse this, you generally shouldn't trust third-party packages with root powers. 

So my real recommended fix is:

```
sudo npm remove -g http-server
npm install -g http-server
```

Alternatively, you can use `npx http-server` whenever you would normally start the server. `npx` will use an installed version if available, or automatically install if it's not available.
