### ISSUE TITLE
Security vulnerability detected

### ISSUE THREAD

**Issue by elabayoub** [http-party/http-server#667]
Hello,

SonarQube is been showing a security issue of level 'Critical'

Filename: http-server:0.12.3 | Reference: CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting') | CVSS Score: 6.1 | Category: CWE-79 | The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page that is served to other users.

Refs: - https://www.owasp.org/index.php/Top_10_2013-A9-Using_Components_with_Known_Vulnerabilities

- https://cwe.mitre.org/data/definitions/937.html

Are there any workarounds ?

Thanks.

**Comment by tomasdev** [comment]
Playing devil's advocate here, but if the page has no inputs, that error isn't a thing. So you have to sanitize the inputs you're using on your side -- not the module.

**Comment by thornjad** [comment]
Correct me if I'm wrong, but this seems like an issue with an application running _on_ http-server, not the server itself? Sanitizing user interaction isn't the responsibility of the server. Indeed, there isn't even much http-server _can_ do.

Please feel free to continue responding in this issue, but i'm closing unless it turns out to be a problem in the server software.
