### ISSUE TITLE
Blocked because of a disallowed MIME type (“text/html”).

### ISSUE THREAD

**Issue by SRF-Audio** [http-party/http-server#673]
I'm developing a music theory web app in VS Code. 

In index.html, I am calling a script using: 
`<script type="module" src="./js/app.js"></script>`.

Then, at the top of app.js I have: 
`import { Note, Scale, Chord } from "../node_modules/@tonaljs";`

More information about @tonaljs: https://github.com/tonaljs/tonal 

The folder structure:

* Chord Generator
  * index.html
  * /js
    * app.js
  * /node_modules
    * /@tonaljs

When I initiate http-server and navigate to Firefox, I get the following error in the Console:

> Loading module from “http://127.0.0.1:8080/Chord%20Generator/node_modules/@tonaljs/” was blocked because of a disallowed MIME type (“text/html”).

Viewing the GET in the Network tab shows that it is indeed being sent as type HTML instead of js. 

I've checked the the directories, and as best I can tell, the references are correct.

Any ideas on how to get this to be correctly seen as a js import?

http-server v0.12.3
npm 6.14.11
Firefox 85
MacOS 11.1
VS Code 1.52.1

**Comment by SheepTester** [comment]
I suspect that it's giving a text/html because you've stumbled upon a directory page (because I'm pretty sure node_modules contains only directories).

If you want to import the JS file itself, you might be able to do

```js
import "../node_modules/@tonaljs/browser/tonal.min.js";
```

which I believe puts `Tonal` in the global scope.

Alternatively, you can use a bundler like [Webpack](https://webpack.js.org/) or [Rollup](https://rollupjs.org/) so you can use `import { Note, Scale } from "@tonaljs/tonal";`

**Comment by thornjad** [comment]
I believe @SheepTester is correct, importing directories does not work by default in the browser, and that has nothing to do with http-server. As far as I can tell from this info, http-server is behaving correctly by serving what I assume is a directory listing HTML page when the directory is requested. Re-open if that really isn't the case
