### ISSUE TITLE
disable favicon error

### ISSUE THREAD

**Issue by yukulele** [http-party/http-server#796]
#### What's the problem this feature will solve?

My browser show this error each time a reload my page:
```error
GET http://127.0.0.1:8080/favicon.ico [[HTTP/1.1 404 Not Found 4ms]]()
```
I only want to see the messages related to the current development.

#### Describe the solution you'd like

http-server should send `HTTP 204 No Content` success status response code by default when `favicon.ico` is not in public directory

#### Alternative Solutions

I can get a favicon.ico file and add it to the directory but
* It's tedious
* I don't want to pollute all my projects with a useless file.

**Comment by zbynek** [comment]
Maybe better to handle this in your code with one of the solutions from https://stackoverflow.com/a/13416784 ? From user's perspective it's better if you can avoid requesting a non-existing file instead of returning an empty answer. Some developers may prefer to see the warning if such redundant requests are made.

**Comment by thornjad** [comment]
If the file doesn't exist, isn't 404 the correct response?

**Comment by shallow-beach** [comment]
I just throw
```
<link rel="icon" href="data:;base64,">
```
into my HTML, which suppresses the favicon fetch error. (Doesn't work in Safari.)
